/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    const [results] = await queryInterface.sequelize.query('SELECT COUNT(*) as count FROM books');

    if (results[0].count > 0) {
      return;
    }

    const now = new Date();
    const books = [
      // Fiction
      {
        isbn: '9780061120084',
        title: 'To Kill a Mockingbird',
        publisher: 'Harper Perennial Modern Classics',
        publication_year: 1960,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780451524935',
        title: '1984',
        publisher: 'Signet Classic',
        publication_year: 1949,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780743273565',
        title: 'The Great Gatsby',
        publisher: 'Scribner',
        publication_year: 1925,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780316769174',
        title: 'The Catcher in the Rye',
        publisher: 'Little, Brown and Company',
        publication_year: 1951,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780142437230',
        title: 'Pride and Prejudice',
        publisher: 'Penguin Classics',
        publication_year: 1901,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780060935467',
        title: 'To the Lighthouse',
        publisher: 'Harcourt',
        publication_year: 1927,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780140283334',
        title: 'One Hundred Years of Solitude',
        publisher: 'Penguin Books',
        publication_year: 1967,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9781400033416',
        title: 'Beloved',
        publisher: 'Vintage',
        publication_year: 1987,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780385490818',
        title: "The Handmaid's Tale",
        publisher: 'Anchor Books',
        publication_year: 1985,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780525478812',
        title: 'The Fault in Our Stars',
        publisher: 'Dutton Books',
        publication_year: 2012,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780345391803',
        title: "The Hitchhiker's Guide to the Galaxy",
        publisher: 'Del Rey',
        publication_year: 1979,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780374292799',
        title: 'The Kite Runner',
        publisher: 'Riverhead Books',
        publication_year: 2003,
        genre: 'Fiction',
        created_at: now,
        updated_at: now,
      },

      // Science Fiction
      {
        isbn: '9780441569595',
        title: 'Dune',
        publisher: 'Ace',
        publication_year: 1965,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780553293357',
        title: 'Foundation',
        publisher: 'Spectra',
        publication_year: 1951,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780765342294',
        title: "Ender's Game",
        publisher: 'Tor Books',
        publication_year: 1985,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780307887443',
        title: 'Ready Player One',
        publisher: 'Random House',
        publication_year: 2011,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780345342966',
        title: 'Neuromancer',
        publisher: 'Ace',
        publication_year: 1984,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780316129084',
        title: 'The Left Hand of Darkness',
        publisher: 'Ace',
        publication_year: 1969,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780553418026',
        title: 'The Martian',
        publisher: 'Broadway Books',
        publication_year: 2011,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780553382563',
        title: 'A Fire Upon the Deep',
        publisher: 'Tor Books',
        publication_year: 1992,
        genre: 'Science Fiction',
        created_at: now,
        updated_at: now,
      },

      // Mystery
      {
        isbn: '9780062073556',
        title: 'And Then There Were None',
        publisher: 'William Morrow',
        publication_year: 1939,
        genre: 'Mystery',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780345538987',
        title: 'The Girl with the Dragon Tattoo',
        publisher: 'Vintage',
        publication_year: 2005,
        genre: 'Mystery',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780307949486',
        title: 'Gone Girl',
        publisher: 'Broadway Books',
        publication_year: 2012,
        genre: 'Mystery',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780316346627',
        title: 'The Silent Patient',
        publisher: 'Celadon Books',
        publication_year: 2019,
        genre: 'Mystery',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780307277671',
        title: 'The Da Vinci Code',
        publisher: 'Anchor',
        publication_year: 2003,
        genre: 'Mystery',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780375725609',
        title: 'Big Little Lies',
        publisher: 'Berkley',
        publication_year: 2014,
        genre: 'Mystery',
        created_at: now,
        updated_at: now,
      },

      // Fantasy
      {
        isbn: '9780547928227',
        title: 'The Hobbit',
        publisher: 'Mariner Books',
        publication_year: 1937,
        genre: 'Fantasy',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780439708180',
        title: "Harry Potter and the Sorcerer's Stone",
        publisher: 'Scholastic',
        publication_year: 1997,
        genre: 'Fantasy',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780553381689',
        title: 'A Game of Thrones',
        publisher: 'Bantam Books',
        publication_year: 1996,
        genre: 'Fantasy',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780765326355',
        title: 'The Name of the Wind',
        publisher: 'DAW Books',
        publication_year: 2007,
        genre: 'Fantasy',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780765350381',
        title: 'The Way of Kings',
        publisher: 'Tor Books',
        publication_year: 2010,
        genre: 'Fantasy',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780060929879',
        title: 'American Gods',
        publisher: 'William Morrow',
        publication_year: 2001,
        genre: 'Fantasy',
        created_at: now,
        updated_at: now,
      },

      // Biography
      {
        isbn: '9780316017923',
        title: 'Steve Jobs',
        publisher: 'Simon & Schuster',
        publication_year: 2011,
        genre: 'Biography',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780743269513',
        title: 'The Autobiography of Benjamin Franklin',
        publisher: 'Simon & Schuster',
        publication_year: 1901,
        genre: 'Biography',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9781451648539',
        title: 'The Diary of a Young Girl',
        publisher: 'Doubleday',
        publication_year: 1947,
        genre: 'Biography',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780743253420',
        title: 'Unbroken',
        publisher: 'Random House',
        publication_year: 2010,
        genre: 'Biography',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780385537858',
        title: 'Educated',
        publisher: 'Random House',
        publication_year: 2018,
        genre: 'Biography',
        created_at: now,
        updated_at: now,
      },

      // History
      {
        isbn: '9780393356182',
        title: 'Sapiens: A Brief History of Humankind',
        publisher: 'Harper',
        publication_year: 2011,
        genre: 'History',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780739326275',
        title: 'Guns, Germs, and Steel',
        publisher: 'W.W. Norton',
        publication_year: 1997,
        genre: 'History',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780385504201',
        title: 'The Devil in the White City',
        publisher: 'Crown',
        publication_year: 2003,
        genre: 'History',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9781476746586',
        title: 'Dead Wake',
        publisher: 'Crown',
        publication_year: 2015,
        genre: 'History',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780307275363',
        title: 'Team of Rivals',
        publisher: 'Simon & Schuster',
        publication_year: 2005,
        genre: 'History',
        created_at: now,
        updated_at: now,
      },

      // Science
      {
        isbn: '9780553380163',
        title: 'A Brief History of Time',
        publisher: 'Bantam Books',
        publication_year: 1988,
        genre: 'Science',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780393319293',
        title: 'The Selfish Gene',
        publisher: 'Oxford University Press',
        publication_year: 1976,
        genre: 'Science',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780345539434',
        title: 'Cosmos',
        publisher: 'Random House',
        publication_year: 1980,
        genre: 'Science',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780385537859',
        title: 'Astrophysics for People in a Hurry',
        publisher: 'W.W. Norton',
        publication_year: 2017,
        genre: 'Science',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780062316097',
        title: 'The Gene: An Intimate History',
        publisher: 'Scribner',
        publication_year: 2016,
        genre: 'Science',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780307908872',
        title: 'The Emperor of All Maladies',
        publisher: 'Scribner',
        publication_year: 2010,
        genre: 'Science',
        created_at: now,
        updated_at: now,
      },

      // Self-Help
      {
        isbn: '9781501144318',
        title: 'Atomic Habits',
        publisher: 'Avery',
        publication_year: 2018,
        genre: 'Self-Help',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9781439167342',
        title: 'How to Win Friends and Influence People',
        publisher: 'Simon & Schuster',
        publication_year: 1936,
        genre: 'Self-Help',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9781416566250',
        title: 'The 7 Habits of Highly Effective People',
        publisher: 'Free Press',
        publication_year: 1989,
        genre: 'Self-Help',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780062457714',
        title: 'The Subtle Art of Not Giving a F*ck',
        publisher: 'HarperOne',
        publication_year: 2016,
        genre: 'Self-Help',
        created_at: now,
        updated_at: now,
      },

      // Philosophy
      {
        isbn: '9780465025275',
        title: "Man's Search for Meaning",
        publisher: 'Beacon Press',
        publication_year: 1946,
        genre: 'Philosophy',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780140449136',
        title: 'Meditations',
        publisher: 'Penguin Classics',
        publication_year: 1901,
        genre: 'Philosophy',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780140449266',
        title: 'The Republic',
        publisher: 'Penguin Classics',
        publication_year: 1901,
        genre: 'Philosophy',
        created_at: now,
        updated_at: now,
      },

      // Horror
      {
        isbn: '9780307743657',
        title: 'The Shining',
        publisher: 'Anchor',
        publication_year: 1977,
        genre: 'Horror',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780451169525',
        title: 'It',
        publisher: 'Signet',
        publication_year: 1986,
        genre: 'Horror',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780316055444',
        title: 'Frankenstein',
        publisher: 'Penguin Classics',
        publication_year: 1901,
        genre: 'Horror',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780140280197',
        title: 'Dracula',
        publisher: 'Penguin Classics',
        publication_year: 1901,
        genre: 'Horror',
        created_at: now,
        updated_at: now,
      },

      // Poetry
      {
        isbn: '9780679783268',
        title: 'The Complete Poems',
        publisher: 'Penguin Classics',
        publication_year: 1955,
        genre: 'Poetry',
        created_at: now,
        updated_at: now,
      },
      {
        isbn: '9780374532741',
        title: 'Milk and Honey',
        publisher: 'Andrews McMeel Publishing',
        publication_year: 2014,
        genre: 'Poetry',
        created_at: now,
        updated_at: now,
      },
    ];

    await queryInterface.bulkInsert('books', books, {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('books', null, {});
  },
};
